repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: local
    hooks:
      - id: swiftlint
        name: SwiftLint
        language: system
        entry: swiftlint lint --strict --quiet
        types: [swift]
        pass_filenames: false
